name: Library Catalog CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x"]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npx playwright install
    - run: node server/server.js &
    - run: npm run start &
    - run: npx playwright test tests/ui.test.js

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Render Deploy Action
    - uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secret.SERVICE_ID }}
        api-key: ${{ secret.RENDERCOM_API_KEY }}
